# Generated by Django 5.2 on 2025-09-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPurpose',
        ),
    ]
